-- MySQL Script generated by MySQL Workbench
-- Fri Apr 25 13:36:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema zarautz_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `zarautz_db` ;

-- -----------------------------------------------------
-- Schema zarautz_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zarautz_db` ;
USE `zarautz_db` ;

-- -----------------------------------------------------
-- Table `zarautz_db`.`documentation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zarautz_db`.`documentation` ;

CREATE TABLE IF NOT EXISTS `zarautz_db`.`documentation` (
  `documentation_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `last_name_one` VARCHAR(45) NOT NULL,
  `last_name_two` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`documentation_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zarautz_db`.`object_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zarautz_db`.`object_category` ;

CREATE TABLE IF NOT EXISTS `zarautz_db`.`object_category` (
  `object_category_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`object_category_id`),
  UNIQUE INDEX `object_category_id_UNIQUE` (`object_category_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zarautz_db`.`object`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zarautz_db`.`object` ;

CREATE TABLE IF NOT EXISTS `zarautz_db`.`object` (
  `object_id` VARCHAR(45) NOT NULL,
  `lost_at` DATETIME NOT NULL,
  `documentation_id` VARCHAR(45) NULL,
  `object_category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`object_id`),
  INDEX `fk_Object_Documentation1_idx` (`documentation_id` ASC) VISIBLE,
  INDEX `fk_Object_Object Category1_idx` (`object_category_id` ASC) VISIBLE,
  UNIQUE INDEX `object_id_UNIQUE` (`object_id` ASC) VISIBLE,
  CONSTRAINT `fk_Object_Documentation1`
    FOREIGN KEY (`documentation_id`)
    REFERENCES `zarautz_db`.`documentation` (`documentation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Object_Object Category1`
    FOREIGN KEY (`object_category_id`)
    REFERENCES `zarautz_db`.`object_category` (`object_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zarautz_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zarautz_db`.`user` ;

CREATE TABLE IF NOT EXISTS `zarautz_db`.`user` (
  `email` VARCHAR(80) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zarautz_db`.`request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zarautz_db`.`request` ;

CREATE TABLE IF NOT EXISTS `zarautz_db`.`request` (
  `request_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `request_at` DATETIME NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  `direction` VARCHAR(200) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `lost_at` DATETIME NOT NULL,
  `place` VARCHAR(100) NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  `object_category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`request_id`),
  INDEX `fk_Request_Object Category_idx` (`object_category_id` ASC) VISIBLE,
  UNIQUE INDEX `request_id_UNIQUE` (`request_id` ASC) VISIBLE,
  CONSTRAINT `fk_Request_Object Category`
    FOREIGN KEY (`object_category_id`)
    REFERENCES `zarautz_db`.`object_category` (`object_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
